### ISSUE TITLE
Unmarshaling an invalid YAML is not throwing an error

### ISSUE THREAD

**Issue by kishorviswanathan** [kubernetes-sigs/yaml#112]
### Summary
Unmarshaling an invalid YAML with `yaml.Unmarshal` populates struct with invalid data rather than returning an error.

### Example
``` go
package main

import (
	"fmt"
	"sigs.k8s.io/yaml"
)

const (
	invalidYAML = `
  test:
test1: hello
`
)

type yamlType struct {
	Test  string `yaml:"test"`
	Test1 string `yaml:"test1"`
}

func main() {
	var data yamlType
	err := yaml.Unmarshal([]byte(invalidYAML), &data)
	if err != nil {
		fmt.Printf("Error %e", err)
	}
	fmt.Printf("data: %+v\n", data)
}
```
Output:
```
data: map[test:<nil>]
```

### Expected output
The function should throw an error since the YAML is not valid.

### Additional Information
* Related issues: https://github.com/open-policy-agent/opa/issues/6854

**Comment by dims** [comment]
try `UnmarshalStrict`

/close

**Comment by kishorviswanathan** [comment]
Makes no difference if this is what you meant.

```go
package main

import (
	"fmt"

	"sigs.k8s.io/yaml"
)

const (
	invalidYAML = `
  test:
test1: hello
`
)

type yamlType struct {
	Test  string `yaml:"test"`
	Test1 string `yaml:"test1"`
}

func main() {
	var data1 interface{}
	err := yaml.UnmarshalStrict([]byte(invalidYAML), &data1)
	if err != nil {
		fmt.Printf("Error1 %e", err)
	}

	fmt.Printf("data1: %+v\n", data1)

	var data2 yamlType
	err = yaml.UnmarshalStrict([]byte(invalidYAML), &data2)
	if err != nil {
		fmt.Printf("Error2 %e", err)
	}
	fmt.Printf("data2: %+v\n", data2)
}
```

Output:
```
data1: map[test:<nil>]
data2: {Test: Test1:}
```

**Comment by kishorviswanathan** [comment]
@dims I am not sure if this issue should remain closed as I was able to reproduce the bug with `UnmarshalStrict` as well. I don't have permission to reopen it.

**Comment by anderseknert** [comment]
I too would want to know more about this behavior. Thanks for looking into it @kishorviswanathan 👍

**Comment by gusega** [comment]
Hi all, any update on this?

**Comment by Seraphyno** [comment]
Hi, I'm also following this thread, currently blocked by this upstream issue as I'm using OPA which relies

**Comment by kishorviswanathan** [comment]
@dims Can you please reopen this issue if you think it is a bug ?
