### ISSUE TITLE
Provide convenience functions like NestedString()

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/yaml#121]
I think it would be handy if this package would support helper functions like the [unstructured package](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured) does.

For example:

```
func NestedString(n Node, fields ...string) (string, bool, error)
func NestedBool(n Node, fields ...string) (bool, bool, error)
func NestedFloat64(n Node, fields ...string) (float64, bool, error)
func NestedInt64(n Node, fields ...string) (int64, bool, error)
func NestedStringSlice(n Node, fields ...string) ([]string, bool, error)
func NestedSlice(n Node, fields ...string) ([]interface{}, bool, error)
func NestedStringMap(n Node, fields ...string) (map[string]string, bool, error)
func NestedNode(n Node, fields ...string) (Node, bool, error)
```

I can provide a PR if you are interested.

**Comment by liggitt** [comment]
Thanks for the issue, but this library is explicitly focused on yaml → json conversions and supporting Kubernetes use cases.

Helpers for direct manipulation of yaml structures is not currently in scope for this library.
