### ISSUE TITLE
Should this library use json-iterator?

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes-sigs/yaml#17]
Kubernetes uses [`github.com/json-iterator/go`](https://github.com/json-iterator/go) instead of `encoding/json`, should this library switch also?

**Comment by dims** [comment]
sure!

**Comment by neolit123** [comment]
/assign
although need to find bandwidth.
i'm yet to check https://github.com/kubernetes-sigs/yaml/issues/15
but i suspect discrepancy between the current backends: yaml2 vs encoding/json.

json-iter does support case sensitive JSON.

**Comment by errordeveloper** [comment]
> json-iter does support case sensitive JSON.

Interesting! So Kubernetes only uses it in part in some performance-critical paths?

**Comment by neolit123** [comment]
> You mean it can detect unknown keys in case-sensitive manner?
yes. i have a PR in the works to enable json-iter.
whether it makes it in is another question as it requires a minor breaking change.

**Comment by neolit123** [comment]
initial reaction was that there is no good justification for this change:
https://github.com/kubernetes-sigs/yaml/pull/19
/lifecycle fronzen

**Comment by neolit123** [comment]
Looks like there is desire to switch k/k away from json iter.

https://github.com/kubernetes/kubernetes/pull/105030

It suggests using a fork of stdlib, that supports the missing valudation features.
