### ISSUE TITLE
Difference with gopkg.in/yaml.v2 when value is passed instead of a reference

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/yaml#30]
It seems that when you pass a struct by value to `Unmarshal`, it silently fails to decode the input data. That seems to be a different and undocumented behavior from `gopkg.in/yaml.v2`, which works both when you pass by value and by reference.

This might be confusing for users, when one changes the import from `gopkg.in/yaml.v2` to `sigs.k8s.io/yaml` and expects that basic things will work the same way.

Reproduce case: https://play.golang.org/p/ucPJWh04AGH

CC @mauriciovasquezbernal

**Comment by neolit123** [comment]
wondering if this is a json-iterator artifact.
sigs.k8s.io/yaml converts YAML to JSON before unmarshaling.

**Comment by invidian** [comment]
Activity.
