### ISSUE TITLE
Can't unmarshal multiple documents

### ISSUE THREAD

**Issue by rmb938** [kubernetes-sigs/yaml#37]
I have a yaml output that has multiple documents that I want to unmarshal.

When I try and unmarshal into a list I get this error

```
JSON: while decoding JSON: json: cannot unmarshal object into Go value of type []v1beta1.CustomResourceDefinition"}
github.com/go-logr/zapr.(*zapLogger).Error
        /home/rbelgrave/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
main.main
        /home/rbelgrave/projects/github.com/rmb938/hostport-allocator/tools/crd-helm/main.go:32
runtime.main
        /home/linuxbrew/.linuxbrew/Cellar/go/1.15/libexec/src/runtime/proc.go:204
exit status 1
```

**Comment by neolit123** [comment]
the library does not support unmarshaling all the documents in an YAML multi doc, but if you pass a multi-doc it should still unmarshall the first document. see here:
https://play.golang.org/p/o-E1IUA7w1x

it manages to unmarshall the first document into `A`, so not sure why are you seeing this error.

if you want to support multi-doc you should split the docs (around `---`) and unmarshall them separatelly.

/triage support

**Comment by rmb938** [comment]
Ah yup I could do it that way.

I did figure out that `gopkg.in/yaml.v2` does support decoding a multi-document yaml via the Decoder. Would it be possible to add that ability to this library?

**Comment by neolit123** [comment]
potentially, but this library is primary used in kubernetes/kubernetes and there we already have code to split the documents and unmarshall separately, so in a way this is not very needed..

i can mark this as a feature request, but contributions would be appreciated.

/remove-triage support
/kind feature
/priority backlog
/help

**Comment by gp42** [comment]
> potentially, but this library is primary used in kubernetes/kubernetes and there we already have code to split the documents and unmarshall separately, so in a way this is not very needed..
> 
> i can mark this as a feature request, but contributions would be appreciated.
> 
> /remove-triage support /kind feature /priority backlog /help

Just in case somebody is looking for this k8s code to split the documents: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/yaml/decoder.go

**Comment by PrayagS** [comment]
Thanks, @gp42.

Used the `YAMLtoJSONDecoder` type to handle the decoding of multiple YAML documents in our CLI application.
