### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by advancedwebdeveloper** [kubernetes-sigs/yaml#41]
Hi.

Got such an issue:
> ~/operator-sdk$ make build
> go build -i -v -x -gcflags "all=-trimpath=/home/oceanfish81" -asmflags "all=-trimpath=/home/oceanfish81" -ldflags " -X 'github.com/operator-framework/operator-sdk/internal/version.Version=v1.1.0+git' -X 'github.com/operator-framework/operator-sdk/internal/version.GitVersion=v1.1.0-16-g33e37efc-dirty' -X 'github.com/operator-framework/operator-sdk/internal/version.GitCommit=33e37efc921bab5cd6b5c84eb68a604d733e06ff' -X 'github.com/operator-framework/operator-sdk/internal/version.KubernetesVersion=v1.18.8' "  -o build ./cmd/{operator-sdk,ansible-operator,helm-operator}
> WORK=/tmp/go-build342156229
> go: downloading sigs.k8s.io/controller-runtime v0.6.3
> \# get https://proxy.golang.org/sigs.k8s.io/controller-runtime/@v/v0.6.3.zip
> go: downloading k8s.io/apimachinery v0.18.8
> \# get https://proxy.golang.org/k8s.io/apimachinery/@v/v0.18.8.zip
> go: downloading github.com/operator-framework/operator-lib v0.1.0
> \# get https://proxy.golang.org/github.com/operator-framework/operator-lib/@v/v0.1.0.zip
> go: downloading k8s.io/client-go v0.18.8
> \# get https://proxy.golang.org/k8s.io/client-go/@v/v0.18.8.zip
> go: downloading sigs.k8s.io/yaml v1.2.0
> \# get https://proxy.golang.org/sigs.k8s.io/yaml/@v/v1.2.0.zip
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7fbb1c2f86b6]
> 
> goroutine 50 [running]:
> x509.loadSystemRoots
> 	/home/oceanfish81/workarea/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/crypto/x509/root_unix.go:81
> x509.initSystemRoots
> 	/home/oceanfish81/workarea/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/crypto/x509/root.go:23
> sync.Once.doSlow
> 	/home/oceanfish81/workarea/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/sync/once.go:66
> sync.Once.Do
> 	/home/oceanfish81/workarea/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/sync/once.go:57
> x509.systemRootsPool
> 	/home/oceanfish81/workarea/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/crypto/x509/root.go:18
> crypto..z2fx509.Certificate.Verify
> 	/home/oceanfish81/workarea/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/crypto/x509/verify.go:776
> crypto..z2ftls.Conn.verifyServerCertificate
> 	/home/oceanfish81/workarea/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/crypto/tls/handshake_client.go:846
> crypto..z2ftls.clientHandshakeStateTLS13.readServerCertificate
> 	/home/oceanfish81/workarea/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/crypto/tls/handshake_client_tls13.go:455
> crypto..z2ftls.clientHandshakeStateTLS13.handshake
> 	/home/oceanfish81/workarea/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/crypto/tls/handshake_client_tls13.go:85
> crypto..z2ftls.Conn.clientHandshake
> 	/home/oceanfish81/workarea/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/crypto/tls/handshake_client.go:209
> crypto..z2ftls.Conn.Handshake
> 	/home/oceanfish81/workarea/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/crypto/tls/conn.go:1362
> http.func2
> 	/home/oceanfish81/workarea/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/net/http/transport.go:1509
> created by net..z2fhttp.persistConn.addTLS
> 	/home/oceanfish81/workarea/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/net/http/transport.go:1505 +0x290
> make: *** [Makefile:60: build] Error 2

Here is my environment:
> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfish81/operator-sdk/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build573184114=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

Here is what I am using:
> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

Could be obtained [here ](https://drive.google.com/file/d/1goBZhc2st89x4LswJivTFOpIbydJUi50/view?usp=sharing)

CC @ianlancetaylor @cherrymui @thanm

**Comment by neolit123** [comment]
The panic seems to happen in libgo under llvm. Can you explain why this is
a problem in this yaml library?

**Comment by ianlancetaylor** [comment]
Is this repeatable?  The backtrace doesn't make much sense.

**Comment by advancedwebdeveloper** [comment]
Hold on, I am heading to reproduce it today (by using a "debug" build of gollvm)
