### ISSUE TITLE
Move from travis to github actions

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/yaml#48]
Travis is going away, so we need to move out CI jobs from travis to github actions
https://github.com/kubernetes-sigs/yaml/blob/master/.travis.yml

There are lots of other k8s projects that have already moved, so would be easy to pick one of them to emulate:
https://cs.k8s.io/?q=jobs%3A&i=nope&files=%5C.github.*&repos=

example the one from klog:
https://github.com/kubernetes/klog/tree/master/.github/workflows

**Comment by viveksyngh** [comment]
I would like to work on this one.

**Comment by nikhita** [comment]
@dims :wave: out of curiosity, is there any particular reason why we would move to use github actions instead of prow?

**Comment by dims** [comment]
@nikhita these are simple jobs, it's easier to write/maintain some basic ci tests without bringing in the hammer. (also reduces cost of our CI as a side effect)

**Comment by longwuyuan** [comment]
https://github.com/kubernetes-sigs/yaml/pull/49
