### ISSUE TITLE
Roundtrip unmarshal/marshal with omitempty failed to restore original yaml

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes-sigs/yaml#56]
As illustrated in #55:

With struct defined as
```
type RoundTripTest struct {
	A []string `json:"a,omitempty"`
}
```
and provided yaml:
```
a: []
```
Unmarshal got:
```
RoundTripTest{A: []string{}}
```
So far things went expected.

But when marshal the unmarshalled struct and got:
```
{}
```
instead of `a: []`

And of course unmarshal again and got:
```
RoundTripTest{A: nil}
```

Feel like a bug but not sure. Is it intended behavior for omitempty?

**Comment by smlx** [comment]
This seems to be intended:

> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string. 

https://pkg.go.dev/encoding/json

**Comment by liggitt** [comment]
agreed, the omitempty directive on a slice or map field collapses empty and null values
