### ISSUE TITLE
yaml marshal sequences indent style

### ISSUE THREAD

**Issue by chenzhiwei** [kubernetes-sigs/yaml#60]
Hello, when I use this package to marshal an object, the format of sequences is:

```
containers:
- name: hello
  image: alpine
```

But seems the suggested format in yaml spec site is:

```
containers:
  - name: hello
    image: alpine
```

I know both of them are fine, but I think it is better to use a widely-used style.

https://yaml.org/spec/1.2/#id2797382

**Comment by neolit123** [comment]
this comes from the yaml.v2 library:
https://github.com/kubernetes-sigs/yaml/blob/master/yaml.go#L11

i don't think there is a way to control it via this wrapping library (kubernetes-sigs/yaml).

/priority backlog
/kind feature
/help
