### ISSUE TITLE
Long strings are marshalled to invalid YAML; incorrect line breaks inserted

### ISSUE THREAD

**Issue by tomasaschan** [kubernetes-sigs/yaml#68]
When serializing an object that contains a very long string in its value, the resulting YAML has line breaks seemingly at random. This seems to be a bug in `gopkg.in/yaml.v2` that is fixed in `gopkg.in/yaml.v3`, but discussions in #18 and #61 seem to imply that migrating is nontrivial.

To reproduce, put the following in a file `repro_test.go`:
```package repro

import (
	"fmt"
	"testing"

	yamlv2 "gopkg.in/yaml.v2"
	yamlv3 "gopkg.in/yaml.v3"
	yamlk8s "sigs.k8s.io/yaml"

	"gotest.tools/assert"
)

func TestYamlV2(t *testing.T) {
	runTest(t, yamlv2.Marshal)
}

func TestYamlV3(t *testing.T) {
	runTest(t, yamlv3.Marshal)
}

func TestYamlK8s(t *testing.T) {
	runTest(t, yamlk8s.Marshal)
}

func runTest(t *testing.T, marshaller func(interface{}) ([]byte, error)) {
	long_string := "a very long string that might have to be broken into multiple lines in order to fit nicely in the output pane"
	j := map[string]string{
		"foo": long_string,
	}
	y, err := marshaller(j)
	if err != nil {
		t.Fatalf("failed converting: %v", err)
	}

	assert.Equal(t, fmt.Sprintf("foo: %s\n", long_string), string(y))
}
```
then run `go mod init; go mod tidy; go test ./...` to see the v2 and k8s tests fail, but not v3:
```
--- FAIL: TestYamlV2 (0.00s)
    repro_test.go:36: assertion failed: 
        --- ←
        +++ →
        @@ -1,2 +1,3 @@
        -foo:·a·very·long·string·that·might·have·to·be·broken·into·multiple·lines·in·order·to·fit·nicely·in·the·output·pane
        +foo:·a·very·long·string·that·might·have·to·be·broken·into·multiple·lines·in·order
        +··to·fit·nicely·in·the·output·pane
         
        
--- FAIL: TestYamlK8s (0.00s)
    repro_test.go:36: assertion failed: 
        --- ←
        +++ →
        @@ -1,2 +1,3 @@
        -foo:·a·very·long·string·that·might·have·to·be·broken·into·multiple·lines·in·order·to·fit·nicely·in·the·output·pane
        +foo:·a·very·long·string·that·might·have·to·be·broken·into·multiple·lines·in·order
        +··to·fit·nicely·in·the·output·pane
```

**Comment by brianpursley** [comment]
There are [plans to fork go-yaml](https://github.com/kubernetes-sigs/yaml/issues/72 ) which should allow this to be fixed in the newly forked repo.

Kustomize has a [similar issue](https://github.com/kubernetes-sigs/kustomize/issues/947) open.

**Comment by KnVerey** [comment]
v2 of go-yaml already exposes the option to change this behaviour. In fact, it was [temporarily the default](https://github.com/go-yaml/yaml/pull/571) in v2.3 of that library, but the change was reverted at the request of the Kubernetes project in v2.4: https://github.com/go-yaml/yaml/pull/670. This repo deliberately opted not to set it by default: https://github.com/kubernetes-sigs/yaml/pull/62#discussion_r713015836. Consumers who want the behaviour change should call `yaml.FutureLineWrap()`. Changing the default would not be possible without a major version bump IMO.

**Comment by brianpursley** [comment]
Thanks for the background @KnVerey 

So in @tomasaschan's original example above, it sounds like this would be a way to avoid wrapping:
```
func TestYamlK8s(t *testing.T) {
        yamlv2.FutureLineWrap()
	runTest(t, yamlk8s.Marshal)
}
```

It's sort of unfortunate how go-yaml implemented that option globally, as there doesn't appear to be a way to unset it or check its value even.

At least `FutureLIneWrap()` is a workaround people can use for now.
