### ISSUE TITLE
Expose a function from sigs.k8s.io/yaml that allows for strict unmarshaling to distinguish between strict and nonstrict errors.

### ISSUE THREAD

**Issue by kevindelgado** [kubernetes-sigs/yaml#70]
Currently, the [kjson library](https://github.com/kubernetes-sigs/json/blob/main/json.go#L96) exposes an `UnmarshalStrict` function that returns strict errors and nonstrict errors separately (strict errors are those relating to unknown fields that are only erroneous when strict unmarshaling is desired and still allow marshaling to occur, while nonstrict errors are any other errors that are always fatal to the marshaling).

We want to expose a similar function from kyaml (sigs.k8s.io/yaml) so that the strict unmarshaling that occurs higher up in the stack does not need to unmarshaling does not need to be performed twice.

For example in the [applyPatcher](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go#L486-L504) of the patch handler, when we want to perform a strict unmarshal, we first do a regular `Unmarshal`, confirm that there are no errors, and then perform a second `StrictUnmarshal` to check for any additional errors that must be strict errors. 

A better approach is to just do a single `UnmarshalStrict` and check the non-strict errors to return fatally (if non-nil) like how we do for kjson.

**Comment by kevindelgado** [comment]
cc @liggitt

**Comment by liggitt** [comment]
For full parity with the strict json parser, we'd need:

* full field paths to duplicate fields encountered
* list of duplicate fields encountered (not just the first)
* avoid terminating early when encountering duplicate fields and return the same decoded content as if non-strict decoding was performed
