### ISSUE TITLE
Request to create an official fork of go-yaml

### ISSUE THREAD

**Issue by natasha41575** [kubernetes-sigs/yaml#72]
Currently, the [go-yaml](https://github.com/go-yaml/yaml) library is used heavily by kubernetes and many subprojects. In kustomize, we use both go-yaml.v2 and go-yaml.v3 as well as this library for all of our yaml processing. 

An update to go-yaml v3 resulted in what would have been a breaking change in kustomize. We talked to the go-yaml maintainer, who agreed to make the fixes, but could not complete them in time for our deadline. As a result, we created a temporary [fork of go-yaml v3](https://github.com/kubernetes-sigs/kustomize/pull/4013) with the intent to remove the fork once the changes were made upstream. More details can be found in this issue: https://github.com/kubernetes-sigs/kustomize/issues/4033

Unfortunately, shortly after we created the fork, the maintainer stopped responding to our issues and did not review the PRs we made to upstream the fix. As I understand it, there is only one go-yaml maintainer and they are very busy. The last response we received was in June 2021: https://github.com/go-yaml/yaml/issues/720#issuecomment-870384621

Maintaining the fork within kustomize is undesirable not only because of the overhead to the kustomize maintainers, but also because kustomize is built into kubectl, so our fork is now also vendored in k/k. It was accepted into kubectl with the understanding that it would be a temporary fork, but now I'm not so sure we will ever be able to remove it. Besides the fixes that we (kustomize) need to have upstream, it seems that we are not the only ones with this problem; there are lots of open issues and PRs in the go-yaml library with no response. 

We would like to propose an official, SIG-sponsored fork of the go-yaml library. I had a very brief [exchange in slack](https://kubernetes.slack.com/archives/C2GL57FJ4/p1642688350045400) about this and I think it's time to push this forward. In that slack exchange I was advised that if we do have this official fork, we would probably want to fold it into this repo, hence why I am creating the issue here. 

I would appreciate some advice on next steps and some indication about whether or not a permanent fork would be acceptable.

cc @liggitt @apelisse @kevindelgado @KnVerey @mengqiy

**Comment by liggitt** [comment]
I'm cautiously in favor, for a couple reasons:
* it lets us prioritize compatibility with yaml.v2 behavior while still picking up yaml.v3 improvements
* it will let us adjust parsing to accomodate information needed by https://github.com/kubernetes-sigs/yaml/issues/70

I would want to structure it similarly to https://sigs.k8s.io/json, where we expose as little of the API surface as possible while still providing the needed functions to callers

**Comment by KnVerey** [comment]
Thanks for filing this, Natasha. I also support this request. Maintaining a fork is not the ideal outcome, but it is better than being unable to make critical fixes to such a key dependency. And if we do need a fork, here makes more sense than inside Kustomize.

> I would want to structure it similarly to https://sigs.k8s.io/json, where we expose as little of the API surface as possible while still providing the needed functions to callers

Just so we're all aware, this may require exposing quite a bit more of the existing surface than you might expect. kyaml extensively uses, and even exposes, the intermediate yaml.Node struct from yaml.v3, for one thing.

**Comment by neolit123** [comment]
in other instances of discussions about the creation of larger internal k8s forks (https://github.com/gogo/protobuf ?) it was noted that the better investment would be to convince the existing (mostly unavailable) maintainers to grant k8s maintainers maintainer rights.

that seems like the better option on paper, has it been considered and communicated outside of github - e.g. via email with the existing maintainers?
if k-sigs/yaml becomes the owner of go-yaml v3 code i'm not convinced a k8s SIG would have the bandwidth to own all incoming topics from attracted new users who see missing feature X in origin.

also worth noting that this repository has not been actively maintained, which can be confirmed by the number of rotted/closed tickets by bots:
https://github.com/kubernetes-sigs/yaml/issues?q=is%3Aissue+is%3Aclosed

**Comment by natasha41575** [comment]
> that seems like the better option on paper, has it been considered and communicated outside of github - e.g. via email with the existing maintainers?
if k-sigs/yaml becomes the owner of go-yaml v3 code i'm not convinced a k8s SIG would have the bandwidth to own all incoming topics from attracted new users who seek missing feature X in origin.

> in other instances of discussions about the creation of larger internal k8s forks (https://github.com/gogo/protobuf ?) it was noted that the better investment would be to convince the existing (mostly unavailable) maintainers to grant k8s maintainers maintainer rights.

Who would we want to add as maintainers to the go-yaml library? To me it seems like we either can:
- add k8s maintainers to the go-yaml maintainer list (maybe), and have them maintain go-yaml upstream. There are effectively no active go-yaml maintainers at the moment, so it would really be just the kubernetes folks maintaining it in this case. 
- fork go-yaml and maintain the fork in one of our SIG repos. 

The maintenance work that would fall on k8s maintainers would be the same in either case, so I'm not convinced that the question of bandwidth is relevant in choosing one of these options over the other. 

Additionally, there are some companies that have strict rules about which repos they can contribute to. Some k8s members can only contribute to kubernetes-sponsored repos. In this case, the fact that the go-yaml code lives elsewhere would be an unnecessary barrier that I would like to remove unless there is some other obvious benefit to _not_ forking.

**Comment by lavalamp** [comment]
Who is volunteering to maintain this new repo?

**Comment by liggitt** [comment]
a subpackage of this repo actually seems like the most natural location if a fork was going to be brought in-org

**Comment by inteon** [comment]
I have some contributions/ improvements that could be of value at some point for the fork (see https://github.com/amurant/go-yaml/tree/v3_next). The main idea in that branch is to add a YAML test-suite & to make the implementation more conformant, based on https://github.com/go-yaml/yaml/pull/798.

**Comment by natasha41575** [comment]
From the SIG API Machinery meeting on 3/9/21, we have reached consensus that this fork would be accepted provided that we add a disclaimer to the README indicating that we will only be accepting a small set of bug fixes, and will not be responsible for any major features. 

Here is a draft of the disclaimer:

### Disclaimer

This package is a fork of the [go-yaml library](https://github.com/go-yaml/yaml) and is intended solely for consumption of kubernetes projects. In this fork, we plan to support only critical changes required for kubernetes, such as small bug fixes and regressions. Larger, general-purpose feature requests should be made in the upstream go-yaml library, and we will reject such changes in this fork unless we are pulling them from upstream.

**Comment by lavalamp** [comment]
That disclaimer LGTM

**Comment by natasha41575** [comment]
@lavalamp @liggitt is there anything else I need to do before submitting a PR to fork?

**Comment by natasha41575** [comment]
/remove-lifecycle rotten

I just updated the corresponding PR yesterday, so this is still in progress!
