### ISSUE TITLE
Marshal ignoring `omitempty` for nested structs

### ISSUE THREAD

**Issue by TimJones** [kubernetes-sigs/yaml#86]
Related to #38 

If I have a nested struct with `omitempty` tag, and nothing declared for that struct, I would expect the whole struct to be omitted, not just the child fields.

Example:
https://go.dev/play/p/3rSbQB9euZT
I would expect the output to be simply
```
b: foo


Program exited.
```

**Comment by liggitt** [comment]
this library uses json marshaling under the covers, so this is a consequence of the golang json encoder also ignoring omitempty on structs (https://github.com/golang/go/issues/9585, https://github.com/golang/go/issues/10648, https://github.com/golang/go/issues/15719, https://github.com/golang/go/issues/42735)

there are a couple proposals to add new options to allow omitting empty structs, but it's not clear if/when they would make progress (https://github.com/golang/go/issues/22480, https://github.com/golang/go/issues/45669)
