### ISSUE TITLE
improve error reporting JSON vs YAML

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/yaml#9]
the errors of this library need work.
with the strict JSON decoder unknown fields would result in errors such as:

```
error unmarshaling JSON: .....: json: unknown field "z";
```

this gives a hint that "z" is unknown.
but the user would first of all be confused why is the error throw to stdout about JSON, while their e.g. manifest is in YAML.

xref: https://github.com/kubernetes-sigs/yaml/pull/7

**Comment by errordeveloper** [comment]
It would be great if we could fix this, the error messages are very very confusing to end-users.

**Comment by neolit123** [comment]
problem here is that all the backends out there including encoding/json yaml.2/3, json-iter don't have good typed errors. this leaves us in a space where we need to parse strings, modify them and return proper errors.

i'm -1 on that, so it's probably best to wait on the backends to fix them, or attempt to push patches upstream.

/remove-kind cleanup
/kind design
/remove-priority important-longterm
/priority backlog

**Comment by neolit123** [comment]
as explained here this is far from ideal:
https://github.com/kubernetes-sigs/yaml/issues/9#issuecomment-487044457

if someone wishes to help please open tickets for yaml v2/v3 and json-iter.
