### ISSUE TITLE
yaml parsing bug

### ISSUE THREAD

**Issue by jon-whit** [kubernetes-sigs/yaml#98]
The following program produces inconsistent yaml parsing results.

```go
package main

import (
	"fmt"

	"google.golang.org/protobuf/types/known/structpb"
	"sigs.k8s.io/yaml"
)

type individualTest struct {
	Context *structpb.Struct
}

type checkTests struct {
	Tests []individualTest
}

func main() {
	yamlInput := `
  tests:
  - context:
       x: 10
       y: 5
  - context:
      "x": 10
      "y": 5`

	var testCases checkTests
	if err := yaml.Unmarshal([]byte(yamlInput), &testCases); err != nil {
		panic(err)
	}

	for _, testCase := range testCases.Tests {
	        fmt.Printf("%v\n", testCase.Context)
	}
}
```

Output:
```
fields:{key:"true"  value:{number_value:5}}  fields:{key:"x"  value:{number_value:10}}
fields:{key:"x"  value:{number_value:10}}  fields:{key:"y"  value:{number_value:5}}
```
Notice that the `y` field (first output line) gets marshalled as a bool `true` 🤔 

Expected Output:
```
fields:{key:"y"  value:{number_value:5}}  fields:{key:"x"  value:{number_value:10}}
fields:{key:"x"  value:{number_value:10}}  fields:{key:"y"  value:{number_value:5}}
```

**Comment by jon-whit** [comment]
Error seems to be stemming form https://github.com/kubernetes-sigs/yaml/blob/master/yaml.go#L278

That converts the `map[string]interface{}{"x": 10, "y": 10}` into `map[interface{}]interface{}{"x": 10, true: 10}`

**Comment by liggitt** [comment]
yaml famously decodes many random strings (`y|Y|yes|Yes|YES|n|N|no|No|NO|true|True|TRUE|false|False|FALSE|on|On|ON|off|Off|OFF`) to booleans :-/

https://yaml.org/type/bool.html#:~:text=A%20Boolean%20represents%20a%20true,Y%20%E2%80%9D%2F%E2%80%9C%20N%20%E2%80%9D.

doing that for key values in a map destined for JSON is certainly not going to work correctly, but I don't have a good sense for how difficult it will be to unwind the decoding for that specific scenario

**Comment by jon-whit** [comment]
@liggitt are you saying that this is not a bug then? I could understand if the parser was interpreting a key `true: "hello"` as a boolean key type when the user intended a string, but the value of this field is very much not a boolean type. I do not understand how a `y` value could be interpreted as a boolean whatsoever.

Could you elaborate further?
