### ISSUE TITLE
Support `yaml` tags

### ISSUE THREAD

**Issue by miparnisari** [kubernetes-sigs/yaml#99]
https://github.com/kubernetes-sigs/yaml/blob/c3772b51db126345efe2dfe4ff8dac83b8141684/README.md?plain=1#L11

 I got bitten by the fact that this is a YAML library but it needs `json` tags. That's not intuitive to me.

Would it be possible to also support `yaml` tags?

**Comment by tamilselvan1102** [comment]
it is very easy Marshal/Unmarshal JSON data to/from Struct object. 
I hope that's why YAML⇔JSON⇔ STRUCT conversion is there.

**Comment by liggitt** [comment]
Thanks for the request, but there is no intent to add yaml tag support. This library is specifically for yaml encoding / decoding of objects with json tags. Adding yaml tag support would introduce new error cases, and break compatibility with existing types that define both yaml and json tags where the yaml name differs from the json name.
